# Generated by Django 6.0.3 on 2026-03-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_purchase_total_cost_sale_saleitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='discount_percent',
            field=models.FloatField(default=0),
        ),
    ]
