# Generated by Django 6.0.3 on 2026-03-11 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_purchaseitem_discount_percent'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(fields=('product', 'size', 'color'), name='unique_product_variant'),
        ),
    ]
