# Generated by Django 6.0.3 on 2026-03-12 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_productvariant_unique_product_variant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='minimun_stock_level',
            new_name='minimum_stock_level',
        ),
    ]
