# Generated by Django 6.0.3 on 2026-03-19 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_rename_minimun_stock_level_inventory_minimum_stock_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.productvariant'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='size',
            field=models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL'), ('XXXXL', 'XXXXL')], max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together={('variant', 'store')},
        ),
    ]
