# Generated by Django 6.0.3 on 2026-03-19 13:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_remove_product_selling_price_product_marked_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='marked_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
