# Generated by Django 6.0.3 on 2026-03-21 16:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_product_marked_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='store',
            constraint=models.UniqueConstraint(fields=('owner', 'store_name', 'location'), name='unique_store_per_owner_location'),
        ),
    ]
