# Generated by Django 6.0.3 on 2026-03-23 15:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_saleitem_cost_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
