# Generated by Django 6.0.3 on 2026-03-23 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_alter_inventory_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
